[package]
name = "dp800"

description = "Rigol DP800 power supply API"
categories = ["hardware-support"]
keywords = ["rigol"]

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
